### ISSUE TITLE
put library things into it's own namespace

### ISSUE THREAD

**Issue by steakhal** [andreihu/asio-fsm#5] opened 2019-07-04 12:01 UTC
`fsm` as a namespace name probably would be a good choice.

**Comment by andreihu** [comment] 2019-07-04 13:50
There are two things to decide here:

- the base namespace name
- name for the current fsm class which is the main interface class of the lib

I'd like to avoid to call the namespace fsm and the interface class fsm, that'd be somehow confusing. I am open to suggestions. As a starter i propose the following:

- namespace name: afsm (shorthand for asio-fsm)
- class name: finite_state_machine

I guess this would be fairly explanatory, has little chance for name collision and users could be spared from typing a lot.

Any ideas

**Comment by steakhal** [comment] 2019-07-04 15:33
The class name sounds good for me. Namespace not so much. If a namespace requires explanation than we probably should look for a better alternative.

It isn't a big deal if the namespace is long. The user can always create an alias to it.

**Comment by andreihu** [comment] 2019-07-18 15:59
Closing it as a duplicate of #13

**Closed** 2019-07-18 15:59 UTC
Labels: enhancement
